### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by jinxx0** [HardyTomas/DDos-Attack-OVH-#10]
Traceback (most recent call last):
  File "80port.py", line 180, in <module>
    'api_key': '1abc234de56fab7c89012d34e56fa7b8'
  File "/usr/local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 748, in create_scraper
    scraper = cls(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 144, in __init__
    super(CloudScraper, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'recaptcha'

**Comment by AFNANAMIN** [comment]
have you find the solution of it plz let me know

**Comment by 0x800080** [comment]
help please with this poblem

**Comment by 0x800080** [comment]
Change recaptcha on captcha

**Comment by rardoz** [comment]
Change recaptcha to captcha in source code works!
