### ISSUE TITLE
plz help boss

### ISSUE THREAD

**Issue by mohandko** [HardyTomas/DDos-Attack-OVH-#17]
Traceback (most recent call last):
  File "80port.py", line 180, in <module>
    'api_key': '1abc234de56fab7c89012d34e56fa7b8'
  File "/usr/local/lib/python3.6/dist-packages/cloudscraper/__init__.py", line 759, in create_scraper
    scraper = cls(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cloudscraper/__init__.py", line 144, in __init__
    super(CloudScraper, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'recaptcha'

**Comment by chatlhs** [comment]
+
