### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by kisukexi21** [HardyTomas/DDos-Attack-OVH-#5]
HELPPPP

Traceback (most recent call last):
  File "443port.py", line 19, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by HardyTomas** [comment]
pip3 install selenium

ср, 22 апр. 2020 г., 16:43 KisukeXI <notifications@github.com>:

**Comment by kisukexi21** [comment]
HEEEELP PLEASE
Traceback (most recent call last):
  File "443port.py", line 29, in <module>
    from toripchanger import TorIpChanger
ModuleNotFoundError: No module named 'toripchanger'

**Comment by HardyTomas** [comment]
pip3 install toripchanger

пт, 24 апр. 2020 г., 15:44 KisukeXI <notifications@github.com>:

**Comment by kisukexi21** [comment]
you guys have video to perform this script ?

**Comment by andress134** [comment]
@HardyTomas  dont help every kid, this kids dont know to install a module but open a stresser service wtf, stop sharing shit ddos scripts  and help kids to promote it

**Comment by GABUT22** [comment]
Help

  File "80port.py", line 31
SyntaxError: Non-ASCII character '\xc3' in file 80port.py on line 31, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
